### ISSUE TITLE
colvis does not exist

### ISSUE THREAD

**Issue by dblyons** [Przemol/seqplots#10]
when I try to make a new plot set, i get the following (error) message and none of the already-loaded tracks display:
Error: The extension ColVis does not exist

Rstudio error log:
Warning: Error in FUN: The extension ColVis does not exist
thanks for the great software - i haven't had any problems with it up until now !

**Comment by Przemol** [comment]
Thanks for feedback!

ColVis extension has been deprecated in DataTables API and subsequently removed from DT >= 1.46 (https://github.com/rstudio/DT/issues/246). I've fixed it temporary by removing this plugin. The hide column button will be back as soon as DT 2.0 is available on CRAN.

Fixed in 49ee44cd305c4b682d23afd770f9edbae9c61dd8
