### ISSUE TITLE
Plot Preview not showing up

### ISSUE THREAD

**Issue by swebb1** [Przemol/seqplots#6]
I have installed seqplots on my machine and running through R-studio. I can upload files and create a new plot set (bigwig and bed files) but I don't see a plot preview when I select these. I can create the plots via the pdf function okay. 

Thanks for your help.

**Comment by Przemol** [comment]
Thanks for bug report.

The issue was caused by incompatibility of seqplots with shiny 0.12.0 update.

It have been fixed since d477332ed1468343b5526c6ab593384db6576030 by introducing new mechanism of checking if plotting preview should be visible.

This commit is now propagated to Bioconductor 3.1 and devel branches.
